### ISSUE TITLE
批量发送文本消息会返回该 returnMsgid not boolean 报错信息

### ISSUE THREAD

**Issue by zhaoguangshuai** [NiZerin/yun-xin-helper#1]
**_报错信息_**
[ERROR] returnMsgid not boolean[180] in /home/vagrant/code/project/competition/vendor/nizerin/yun-xin-helper/src/Api/Base.php
[ERROR] #0 /home/vagrant/code/project/competition/vendor/nizerin/yun-xin-helper/src/Api/Chat.php(800): YunXinHelper\Api\Base->sendRequest('msg/sendBatchMs...', Array)
#1 /home/vagrant/code/project/competition/vendor/nizerin/yun-xin-helper/src/Api/Chat.php(851): YunXinHelper\Api\Chat->sendBatchMsg('account_2002002...', Array, 0, '{"msg":{"send_t...', '', '', Array, '', '', NULL, true)

**_解决办法_**
![image](https://user-images.githubusercontent.com/39761773/84973917-cba24500-b154-11ea-9e9d-c5753dbbed64.png)

**Comment by ghost** [comment]
[fixed](https://github.com/NiZerin/yun-xin-helper/pull/2)
